# Generated by Django 4.2.13 on 2024-09-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('numero_lugar', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='lugares/')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('numero_caja', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cajas/')),
                ('url', models.URLField()),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('etiqueta_qr', models.ImageField(blank=True, null=True, upload_to='etiquetas_qr/')),
                ('nota', models.TextField(blank=True, null=True)),
                ('localizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='catalog.lugar')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('numero_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos/')),
                ('unidades', models.IntegerField(blank=True, null=True)),
                ('fecha_compra', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('en_uso', models.BooleanField(default=False)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.caja')),
            ],
        ),
    ]
