# Generated by Django 4.2.13 on 2024-09-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='localizacion',
        ),
    ]
